[package]
name = "mux"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive = { git = "https://github.com/Banyc/primitive.git", tag = "v0.0.56" }
tokio = { version = "1", features = ["full"] }
